management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

config:
  hello: hello im config dev