spring:
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
